### ISSUE TITLE
Show Sha and md5 hash

### ISSUE THREAD

**Issue by niccokunzmann** [freifunk-berlin/util.berlin.freifunk.net#2]
Context: When I upload the firmware to a router, they usually show the  md5 hash or the sha hash. I want to see if the image has any errors.
Problem: I can not find the md5 hash for downloaded images.

- Hint: This can be hidden and shown without JavaScript just as Checkbutton and styling. [source](http://lists.astaup.de/pipermail/uplug/2017-January/007617.html)

![image](https://cloud.githubusercontent.com/assets/564768/24083598/509adba0-0cda-11e7-8f5e-4cf42e8b5eef.png)

**Comment by SvenRoederer** [comment]
please also check https://github.com/freifunk-berlin/firmware/issues/413 which might cause trouble mapping the filenames
