### ISSUE TITLE
hardware-listing: don't lists images when hardware was renamed

### ISSUE THREAD

**Issue by SvenRoederer** [freifunk-berlin/util.berlin.freifunk.net#4]
for some routers the filnename (id-string) changes and breaks the automatic mapping. currently affected models are:
  * TPLink WR841(N,ND) which have hardware-strings like ```wr841```, ```wr841n``` and ```wr841nd```
  * TPlink CPE210, which has hardwarename of ```cpe210-220-510-520``` (OpenWrt-based) and ```cpe210-220``` (LEDE-based) 
  * TPlink CPE510, which has hardwarename of ```cpe210-220-510-520``` (OpenWrt-based) and ```cpe510-520``` (LEDE-based) 

Reasons are: varying names from upstream

This ends up, that the automatic mapping ```$hardware``` to the filename will not work for all builds automatically. (```$search = $hardware."-factory";``` https://github.com/freifunk-berlin/util.berlin.freifunk.net/blob/master/www/hardware.php#L46) and some images will not be avail in the webpage.

This can by solved by eighter 
  * having something hardcoded , like https://github.com/freifunk-berlin/util.berlin.freifunk.net/blob/master/www/hardware.php#L33
  * having an (external) table this looks up some hints to support the automatic mapping

**Comment by SvenRoederer** [comment]
I prefer an external file, maybe CSV to separate this from the pure code

**Comment by sarumpaet** [comment]
For the time being I added another hack in 8505b2c. I think the proper (and simple) solution would be supporting `name=cpe210-220-510-520,cpe510-520` - I'll implement that in case something like this comes up again. Closing for now.

**Comment by SvenRoederer** [comment]
Do we also want to have EdgeRouterX-images avail via this script?
As their naming is ```...-ubnt-erx-squashfs-sysupgrade.tar```

**Comment by sarumpaet** [comment]
Added in 4c11a7b
