### ISSUE TITLE
hardware.php is not listing "EU", "US" and "Intl" firmwares for Archer C7 and others

### ISSUE THREAD

**Issue by SvenRoederer** [freifunk-berlin/util.berlin.freifunk.net#7]
as of FCC-rules TPlink is shipping regoin-branded firmwares. these need different factory-images to pass sanity-check.

These images are build (```squashfs-eu-factory.bin```) but not linked on the page. See https://lists.berlin.freifunk.net/pipermail/berlin/2017-June/035901.html

Maybe we should think of adding "subsections" on the page for each regional-type

**Comment by sarumpaet** [comment]
fixed in 9cd42f4
